Add test runs to pre-commit hook Ensure that "-q" option is really quiet

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -7,3 +7,11 @@ if [ $RESULT -ne 0 ]; then
     echo "pylint issues found, aborting"
     exit 1
 fi
+
+./run-tests.py -q
+RESULT=$?
+
+if [ $RESULT -ne 0 ]; then
+    echo "Tests are not passing, aborting"
+    exit 1
+fi
